// <auto-generated />
using System;
using DaVinci.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace DaVinci.Migrations
{
    [DbContext(typeof(OracleFIAPDbContext))]
    partial class OracleFIAPDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DaVinci.Models.Clientes", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasAnnotation("Cidade", "Cidade do cliente é obrigatorio");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasAnnotation("Cpf", "CPF do cliente é obrigatorio");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasAnnotation("Email", "Email do cliente é obrigatorio");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasAnnotation("Nome", "Nome do cliente é obrigatorio");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasAnnotation("Sexo", "Sexo do cliente é obrigatorio");

                    b.HasKey("IdCliente");

                    b.ToTable("TB_DV_CLIENTE", (string)null);
                });

            modelBuilder.Entity("DaVinci.Models.Feedbacks", b =>
                {
                    b.Property<int>("IdFeedback")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFeedback"));

                    b.Property<int>("Avaliacao")
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Avaliacao", "Avaliação do feedback é obrigatorio");

                    b.Property<int?>("ClienteIdCliente")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasAnnotation("Comentario", "Comentario do feedback é obrigatorio");

                    b.Property<DateTime>("DataFeedback")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasAnnotation("DataFeedback", "Data do feedback é obrigatorio");

                    b.Property<int>("IdCliente")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdProduto")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("ProdutoIdProduto")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdFeedback");

                    b.HasIndex("ClienteIdCliente");

                    b.HasIndex("ProdutoIdProduto");

                    b.ToTable("TB_DV_FEEDBACK", (string)null);
                });

            modelBuilder.Entity("DaVinci.Models.Produtos", b =>
                {
                    b.Property<int>("IdProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduto"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasAnnotation("Categoria", "Categoria do produto é obrigatorio");

                    b.Property<int?>("ClienteIdCliente")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdCliente")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasAnnotation("Modelo", "Modelo do produto é obrigatorio");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasAnnotation("Nome", "Nome do produto é obrigatorio");

                    b.Property<decimal>("Valor")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasAnnotation("Valor", "Valor do produto é obrigatorio");

                    b.HasKey("IdProduto");

                    b.HasIndex("ClienteIdCliente");

                    b.ToTable("TB_DV_PRODUTO", (string)null);
                });

            modelBuilder.Entity("DaVinci.Models.Feedbacks", b =>
                {
                    b.HasOne("DaVinci.Models.Clientes", "Cliente")
                        .WithMany("Feedbacks")
                        .HasForeignKey("ClienteIdCliente");

                    b.HasOne("DaVinci.Models.Produtos", "Produto")
                        .WithMany("Feedbacks")
                        .HasForeignKey("ProdutoIdProduto");

                    b.Navigation("Cliente");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("DaVinci.Models.Produtos", b =>
                {
                    b.HasOne("DaVinci.Models.Clientes", "Cliente")
                        .WithMany("Produtos")
                        .HasForeignKey("ClienteIdCliente");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("DaVinci.Models.Clientes", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("DaVinci.Models.Produtos", b =>
                {
                    b.Navigation("Feedbacks");
                });
#pragma warning restore 612, 618
        }
    }
}
